### ISSUE TITLE
Searching by battlenet:// link throws a 400 error

### ISSUE THREAD

**Issue by joshleblanc** [nephest/sc2-ladder-generator#57]
Example input: battlenet:://starcraft/profile/2/11108538663170998272

Result:
![image](https://user-images.githubusercontent.com/1729810/212546542-0cb86492-4f20-4607-a00d-cd8bb7ea7227.png)

**Comment by nephest** [comment]
Yep it's a bug. I'll start working on it right away.

**Comment by nephest** [comment]
The issue should be resolved now.

Searching by provided input `battlenet:://starcraft/profile/2/11108538663170998272` returns an empty result set because not all players are indexed by this search. Please try searching for other profiles until you find a match to confirm that the issue has indeed been resolved.
